// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLNIhZo82ww0LS9W0gP9JVrJq8u8Wm8ZM',
    appId: '1:308547970885:web:75d56278c99980b764402c',
    messagingSenderId: '308547970885',
    projectId: 'ullamki',
    authDomain: 'ullamki.firebaseapp.com',
    storageBucket: 'ullamki.appspot.com',
    measurementId: 'G-MV65FYDF53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsh-H45JJ8-2ZuLg80PEUvSaBkpKC9uRM',
    appId: '1:308547970885:android:5db39947c84bdbc364402c',
    messagingSenderId: '308547970885',
    projectId: 'ullamki',
    storageBucket: 'ullamki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXoC3YBtQOxvTgXmyz7yYHPq0jF2D3ZMU',
    appId: '1:308547970885:ios:5fb1204a4608b79164402c',
    messagingSenderId: '308547970885',
    projectId: 'ullamki',
    storageBucket: 'ullamki.appspot.com',
    iosClientId: '308547970885-ajo754q2bnungvuubhpeltqh5d55igvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ullamki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXoC3YBtQOxvTgXmyz7yYHPq0jF2D3ZMU',
    appId: '1:308547970885:ios:6769ab3fc89cb14664402c',
    messagingSenderId: '308547970885',
    projectId: 'ullamki',
    storageBucket: 'ullamki.appspot.com',
    iosClientId: '308547970885-09fn6q4itp40m99llnem7sdifrj2h28s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ullamki.RunnerTests',
  );
}
